export const GET_RECIPES_START = "GET_RECIPES_START";
export const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
export const GET_RECIPES_FAIL = "GET_RECIPES_FAIL";

export const GET_RECIPES_COUNT_START = "GET_RECIPES_COUNT_START";
export const GET_RECIPES_COUNT_SUCCESS = "GET_RECIPES_COUNT_SUCCESS";

export const GET_RECIPE_START = "GET_RECIPE_START";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_FAIL = "GET_RECIPE_FAIL";

export const GET_CATEGORIES_START = "GET_CATEGORIES_START";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";

export const UPDATE_FILTER = "UPDATE_FILTER";
