export const GET_MD_RECIPES_START = "GET_MD_RECIPES_START";
export const GET_MD_RECIPES_SUCCESS = "GET_MD_RECIPES_SUCCESS";
export const GET_MD_RECIPES_FAIL = "GET_MD_RECIPES_FAIL";

export const GET_MD_RECIPES_COUNT_START = "GET_MD_RECIPES_COUNT_START";
export const GET_MD_RECIPES_COUNT_SUCCESS = "GET_MD_RECIPES_COUNT_SUCCESS";

export const GET_MD_RECIPE_START = "GET_MD_RECIPE_START";
export const GET_MD_RECIPE_SUCCESS = "GET_MD_RECIPE_SUCCESS";
export const GET_MD_RECIPE_FAIL = "GET_MD_RECIPE_FAIL";

export const DELETE_MD_RECIPE_START = "DELETE_MD_RECIPE_START";
export const DELETE_MD_RECIPE_SUCCESS = "DELETE_MD_RECIPE_SUCCESS";
export const DELETE_MD_RECIPE_FAIL = "DELETE_MD_RECIPE_FAIL";

export const GET_MD_CATEGORIES_START = "GET_MD_CATEGORIES_START";
export const GET_MD_CATEGORIES_SUCCESS = "GET_MD_CATEGORIES_SUCCESS";
export const GET_MD_CATEGORIES_FAIL = "GET_MD_CATEGORIES_FAIL";

export const UPDATE_MD_FILTER = "UPDATE_FILTER";
