export const GET_MD_RECIPES_START = "GET_MD_RECIPES_START";
export const GET_MD_RECIPES_SUCCESS = "GET_MD_RECIPES_SUCCESS";
export const GET_MD_RECIPES_FAIL = "GET_MD_RECIPES_FAIL";

export const GET_MD_RECIPES_COUNT_START = "GET_MD_RECIPES_COUNT_START";
export const GET_MD_RECIPES_COUNT_SUCCESS = "GET_MD_RECIPES_COUNT_SUCCESS";

export const UPDATE_MD_FILTER = "UPDATE_MD_FILTER";
