export const GET_AC_RECIPES_START = "GET_AC_RECIPES_START";
export const GET_AC_RECIPES_SUCCESS = "GET_AC_RECIPES_SUCCESS";
export const GET_AC_RECIPES_FAIL = "GET_AC_RECIPES_FAIL";

export const GET_AC_RECIPES_COUNT_START = "GET_AC_RECIPES_COUNT_START";
export const GET_AC_RECIPES_COUNT_SUCCESS = "GET_AC_RECIPES_COUNT_SUCCESS";

export const UPDATE_AC_FILTER = "UPDATE_AC_FILTER";
