export const GET_AC_RECIPES_START = "GET_AC_RECIPES_START";
export const GET_AC_RECIPES_SUCCESS = "GET_AC_RECIPES_SUCCESS";
export const GET_AC_RECIPES_FAIL = "GET_AC_RECIPES_FAIL";

export const GET_AC_RECIPES_COUNT_START = "GET_AC_RECIPES_COUNT_START";
export const GET_AC_RECIPES_COUNT_SUCCESS = "GET_AC_RECIPES_COUNT_SUCCESS";

export const GET_AC_CATEGORIES_START = "GET_AC_CATEGORIES_START";
export const GET_AC_CATEGORIES_SUCCESS = "GET_AC_CATEGORIES_SUCCESS";
export const GET_AC_CATEGORIES_FAIL = "GET_AC_CATEGORIES_FAIL";

export const GET_AC_RECIPE_START = "GET_AC_RECIPE_START";
export const GET_AC_RECIPE_SUCCESS = "GET_AC_RECIPE_SUCCESS";
export const GET_AC_RECIPE_FAIL = "GET_AC_RECIPE_FAIL";
